### PR TITLE
feat!: First Release

### PR DESCRIPTION
**Pull request by shiipou**
This will publish the first release of the action. (To be out of beta version on this action who seams to be stable enough referring the time we use it)

### CODE REVIEW

**Comment by shiipou** [comment]
This release will be published after the Actionhackathon21 results, because we got some minor change to the doc to make it perfect.

**Comment by shiipou** [comment]
@lenra-io/lenra Did you think the workflow defined in each repository to manage dependencies which create `Update dependency` Pull Requests work well or did you see any bugs that can block the release of the first public version ?

**Comment by jonas-martinez** [comment]
@shiipou
Personally I found that this workflow worked quite well, I don't have any suggestion for the moment 👍

**Pull request merged**
